# pg_hba.conf — autenticación para clase01-intro

# Acceso local del proceso postgres
local   all             all                                     trust

# Acceso desde localhost para alumnos y herramientas
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Replicación streaming (replicador → primaria)
host    replication     replicator      0.0.0.0/0               md5

# Acceso desde red interna de Docker (contenedores entre sí)
host    all             all             0.0.0.0/0               md5
